=== czertbytes/tarsius/tarsius-updater/src/main/resources/data/add/add.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ Copyright (c) 2011 by Daniel Hodan <daniel.hodan@anyd.cz>.
  ~
  ~ This file is part of Tarsius.
  ~
  ~ Tarsius is free software; you can redistribute it and/or modify
  ~ it under the terms of the GNU General Public License as published by
  ~ the Free Software Foundation, either version 3 of the License, or
  ~ (at your option) any later version.
  ~
  ~ Tarsius is distributed in the hope that it will be useful,
  ~ but WITHOUT ANY WARRANTY; without even the implied warranty of
  ~ MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  ~ GNU General Public License for more details.
  ~
  ~ You should have received a copy of the GNU General Public License
  ~ along with Tarsius. If not, see <http://www.gnu.org/licenses/>.
  -->
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="add" type="addType"/>

    <xs:complexType name="addType">
        <xs:sequence>
            <xs:element type="xs:string" name="description" minOccurs="1" maxOccurs="1"/>
            <xs:element type="packageType" name="package" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element type="distributionType" name="distribution" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="packageType">
        <xs:sequence>
            <xs:element type="parserType" name="parser"/>
            <xs:element type="tagsType" name="tags"/>
        </xs:sequence>
        <xs:attribute type="xs:string" name="name" use="required"/>
    </xs:complexType>

    <xs:complexType name="parserType">
        <xs:sequence>
            <xs:element type="xs:string" name="param1" minOccurs="0" maxOccurs="1"/>
            <xs:element type="xs:string" name="param2" minOccurs="0" maxOccurs="1"/>
            <xs:element type="xs:string" name="param3" minOccurs="0" maxOccurs="1"/>
        </xs:sequence>
        <xs:attribute type="xs:string" name="class" use="required"/>
    </xs:complexType>

    <xs:complexType name="tagsType">
        <xs:sequence>
            <xs:element name="tag" maxOccurs="unbounded" minOccurs="1"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="distributionType">
        <xs:sequence>
            <xs:element type="parserType" name="parser"/>
        </xs:sequence>
        <xs:attribute type="xs:string" name="version"/>
        <xs:attribute type="xs:string" name="release_name"/>
        <xs:attribute type="xs:string" name="homepage"/>
    </xs:complexType>

</xs:schema>

=== czertbytes/tarsius/tarsius-updater/src/main/resources/data/add/packages_system.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!--
  ~ Copyright (c) 2011 by Daniel Hodan <daniel.hodan@anyd.cz>.
  ~
  ~ This file is part of Tarsius.
  ~
  ~ Tarsius is free software; you can redistribute it and/or modify
  ~ it under the terms of the GNU General Public License as published by
  ~ the Free Software Foundation, either version 3 of the License, or
  ~ (at your option) any later version.
  ~
  ~ Tarsius is distributed in the hope that it will be useful,
  ~ but WITHOUT ANY WARRANTY; without even the implied warranty of
  ~ MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  ~ GNU General Public License for more details.
  ~
  ~ You should have received a copy of the GNU General Public License
  ~ along with Tarsius. If not, see <http://www.gnu.org/licenses/>.
  -->

<add xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="add.xsd">

    <description>System packages</description>

    <package name="linux-kernel">
        <parser class="cz.anyd.updater.parser.app.HtmlPageParser">
            <param1>http://www.kernel.org/kdist/finger_banner</param1>
            <param2><![CDATA[The latest stable (?:.*) version of the Linux kernel is:\s+(.*?)]]></param2>
        </parser>
        <tags>
            <tag>linux</tag>
            <tag>kernel</tag>
            <tag>system</tag>
        </tags>
    </package>

    <package name="grub2">
        <parser class="cz.anyd.updater.parser.app.FtpDirectoryListParser">
            <param1>alpha.gnu.org</param1>
            <param2>gnu/grub</param2>
            <param3><![CDATA[grub-([^-]*?).tar.gz]]></param3>
        </parser>
        <tags>
            <tag>grub</tag>
            <tag>system</tag>
        </tags>
    </package>

    <package name="udev">
        <parser class="cz.anyd.updater.parser.app.FtpDirectoryListParser">
            <param1>kernel.org</param1>
            <param2>pub/linux/utils/kernel/hotplug</param2>
            <param3><![CDATA[udev-([^-]*?).tar.gz]]></param3>
        </parser>
        <tags>
            <tag>udev</tag>
            <tag>system</tag>
        </tags>
    </package>

    <package name="dbus">
        <parser class="cz.anyd.updater.parser.app.HtmlPageParser">
            <param1>http://www.freedesktop.org/wiki/Software/dbus</param1>
            <param2><![CDATA[latest stable release is <a class="http" href="http://dbus.freedesktop.org/releases/dbus/dbus-(?:.*?).tar.gz">D-Bus (.*?)</a>]]></param2>
        </parser>
        <tags>
            <tag>dbus</tag>
            <tag>system</tag>
        </tags>
    </package>

    <package name="pam">
        <parser class="cz.anyd.updater.parser.app.FtpDirectoryListParser">
            <param1>ftp.kernel.org</param1>
            <param2>pub/linux/libs/pam/library</param2>
            <param3><![CDATA[_LATEST_IS_Linux-PAM-(.*?)]]></param3>
        </parser>
        <tags>
            <tag>pam</tag>
            <tag>system</tag>
        </tags>
    </package>

    <package name="oss">
        <parser class="cz.anyd.updater.parser.app.HtmlPageParser">
            <param1>http://www.opensound.com/linux.html</param1>
            <param2><![CDATA[OSS (.*?) for Linux ]]></param2>
        </parser>
        <tags>
            <tag>oss</tag>
            <tag>system</tag>
            <tag>sound system</tag>
        </tags>
    </package>

    <package name="alsa">
        <parser class="cz.anyd.updater.parser.app.HtmlPageParser">
            <param1>http://www.alsa-project.org/main/index.php/Main_Page</param1>
            <param2><![CDATA[alsa (.*?) release | ]]></param2>
        </parser>
        <tags>
            <tag>alsa</tag>
            <tag>system</tag>
            <tag>sound system</tag>
        </tags>
    </package>

    <package name="dkms">
        <parser class="cz.anyd.updater.parser.app.HtmlPageParser">
            <param1>http://linux.dell.com/dkms/</param1>
            <param2><![CDATA[The latest stable version is: (.*?)<br>]]></param2>
        </parser>
        <tags>
            <tag>dkms</tag>
            <tag>system</tag>
        </tags>
    </package>

    <package name="bluez">
        <parser class="cz.anyd.updater.parser.app.HtmlPageParser">
            <param1>http://www.bluez.org/</param1>
            <param2><![CDATA[bluez-(.*?).tar.gz</a>]]></param2>
        </parser>
        <tags>
            <tag>bluez</tag>
            <tag>system</tag>
        </tags>
    </package>

    <package name="nss">
        <parser class="cz.anyd.updater.parser.app.HtmlPageParser">
            <param1>http://www.mozilla.org/projects/security/pki/nss/</param1>
            <param2><![CDATA[NSS (.*?) Release</a>]]></param2>
        </parser>
        <tags>
            <tag>nss</tag>
            <tag>system</tag>
        </tags>
    </package>

</add>

=== czertbytes/tarsius/tarsius-updater/src/main/resources/data/add/packages_web_server.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!--
  ~ Copyright (c) 2011 by Daniel Hodan <daniel.hodan@anyd.cz>.
  ~
  ~ This file is part of Tarsius.
  ~
  ~ Tarsius is free software; you can redistribute it and/or modify
  ~ it under the terms of the GNU General Public License as published by
  ~ the Free Software Foundation, either version 3 of the License, or
  ~ (at your option) any later version.
  ~
  ~ Tarsius is distributed in the hope that it will be useful,
  ~ but WITHOUT ANY WARRANTY; without even the implied warranty of
  ~ MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  ~ GNU General Public License for more details.
  ~
  ~ You should have received a copy of the GNU General Public License
  ~ along with Tarsius. If not, see <http://www.gnu.org/licenses/>.
  -->

<add xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="add.xsd">

    <description>Web Server packages</description>

    <package name="httpd">
        <parser class="cz.anyd.updater.parser.app.HtmlPageParser">
            <param1>http://httpd.apache.org/download.cgi</param1>
            <param2><![CDATA[<a(?:[^>]*)>httpd-(.*?).tar.gz<\/a>]]></param2>
        </parser>
        <tags>
            <tag>httpd</tag>
            <tag>web server</tag>
        </tags>
    </package>

    <package name="lighttpd">
        <parser class="cz.anyd.updater.parser.app.HtmlPageParser">
            <param1>http://www.lighttpd.net/download/</param1>
            <param2><![CDATA[lighttpd-(.*?).tar.gz]]></param2>
        </parser>
        <tags>
            <tag>lighttpd</tag>
            <tag>web server</tag>
        </tags>
    </package>

    <package name="yaws">
        <parser class="cz.anyd.updater.parser.app.HtmlPageParser">
            <param1>http://yaws.hyber.org/</param1>
            <param2><![CDATA[Yaws (.*?)\s+<\/h3>]]></param2>
        </parser>
        <tags>
            <tag>yaws</tag>
            <tag>web server</tag>
        </tags>
    </package>

    <package name="cherokee">
        <parser class="cz.anyd.updater.parser.app.HtmlPageParser">
            <param1>http://www.cherokee-project.com/download/</param1>
            <param2><![CDATA[<a(?:[^>]*)>LATEST_is_(.*?)<\/a>]]></param2>
        </parser>
        <tags>
            <tag>cherokee</tag>
            <tag>web server</tag>
        </tags>
    </package>

    <package name="nginx">
        <parser class="cz.anyd.updater.parser.app.HtmlPageParser">
            <param1>http://nginx.org/en/download.html</param1>
            <param2><![CDATA[nginx-(.*?).tar.gz]]></param2>
        </parser>
        <tags>
            <tag>nginx</tag>
            <tag>web server</tag>
        </tags>
    </package>

</add>

=== czertbytes/tarsius/tarsius-updater/src/main/resources/data/add/packages_text_editor.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!--
  ~ Copyright (c) 2011 by Daniel Hodan <daniel.hodan@anyd.cz>.
  ~
  ~ This file is part of Tarsius.
  ~
  ~ Tarsius is free software; you can redistribute it and/or modify
  ~ it under the terms of the GNU General Public License as published by
  ~ the Free Software Foundation, either version 3 of the License, or
  ~ (at your option) any later version.
  ~
  ~ Tarsius is distributed in the hope that it will be useful,
  ~ but WITHOUT ANY WARRANTY; without even the implied warranty of
  ~ MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  ~ GNU General Public License for more details.
  ~
  ~ You should have received a copy of the GNU General Public License
  ~ along with Tarsius. If not, see <http://www.gnu.org/licenses/>.
  -->

<add xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="add.xsd">

    <description>Text editor packages</description>

    <package name="vim">
        <parser class="cz.anyd.updater.parser.app.HtmlPageParser">
            <param1>http://www.vim.org/index.html</param1>
            <param2><![CDATA[Vim\n(.*?)\s+is the current version]]></param2>
        </parser>
        <tags>
            <tag>vim</tag>
            <tag>text editor</tag>
            <tag>tui</tag>
        </tags>
    </package>

    <package name="emacs">
        <parser class="cz.anyd.updater.parser.app.HtmlPageParser">
            <param1>http://www.gnu.org/software/emacs</param1>
            <param2><![CDATA[<b>The current stable release is (.*?)<\/b>]]></param2>
        </parser>
        <tags>
            <tag>emacs</tag>
            <tag>text editor</tag>
            <tag>tui</tag>
        </tags>
    </package>

    <package name="ed">
        <parser class="cz.anyd.updater.parser.app.FtpDirectoryListParser">
            <param1>ftp.gnu.org</param1>
            <param2>/gnu/ed</param2>
            <param3><![CDATA[ed-(.*?).tar.gz]]></param3>
        </parser>
        <tags>
            <tag>ed</tag>
            <tag>text editor</tag>
            <tag>tui</tag>
        </tags>
    </package>

    <package name="nano">
        <parser class="cz.anyd.updater.parser.app.HtmlPageParser">
            <param1>http://www.nano-editor.org</param1>
            <param2><![CDATA[Latest Version\s+(.*?) \(stable\)]]></param2>
        </parser>
        <tags>
            <tag>nano</tag>
            <tag>text editor</tag>
            <tag>tui</tag>
        </tags>
    </package>

    <package name="jedit">
        <parser class="cz.anyd.updater.parser.app.HtmlPageParser">
            <param1>http://www.jedit.org</param1>
            <param2><![CDATA[Stable Version: <a(?:[^>]*)>(.*?)<\/a>]]></param2>
        </parser>
        <tags>
            <tag>jedit</tag>
            <tag>text editor</tag>
            <tag>gui</tag>
            <tag>java</tag>
        </tags>
    </package>

    <package name="gedit">
        <parser class="cz.anyd.updater.parser.app.HtmlPageParser">
            <param1>http://projects.gnome.org/gedit/index.html</param1>
            <param2><![CDATA[The latest stable release is <a(?:[^>]*)>(.*?)<\/a>]]></param2>
        </parser>
        <tags>
            <tag>gedit</tag>
            <tag>text editor</tag>
            <tag>gui</tag>
            <tag>gtk</tag>
            <tag>gnome</tag>
        </tags>
    </package>

    <package name="scite">
        <parser class="cz.anyd.updater.parser.app.HtmlPageParser">
            <param1>http://www.scintilla.org/SciTEDownload.html</param1>
            <param2><![CDATA[<h2(?:[^>]*)>\s+Release (.*?)\s+<\/h2>]]></param2>
        </parser>
        <tags>
            <tag>scite</tag>
            <tag>text editor</tag>
            <tag>gui</tag>
            <tag>gtk</tag>
        </tags>
    </package>

    <package name="leafpad">
        <parser class="cz.anyd.updater.parser.app.HtmlPageParser">
            <param1>http://tarot.freeshell.org/leafpad/index.html</param1>
            <param2><![CDATA[<a(?:[^>]*)>leafpad-(.*?).tar.gz<\/a>]]></param2>
        </parser>
        <tags>
            <tag>leafpad</tag>
            <tag>text editor</tag>
            <tag>gui</tag>
            <tag>gtk</tag>
        </tags>
    </package>

</add>
