=== czertbytes/tarsius/tarsius-updater/src/main/resources/data/add/add.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ Copyright (c) 2011 by Daniel Hodan <daniel.hodan@anyd.cz>.
  ~
  ~ This file is part of Tarsius.
  ~
  ~ Tarsius is free software; you can redistribute it and/or modify
  ~ it under the terms of the GNU General Public License as published by
  ~ the Free Software Foundation, either version 3 of the License, or
  ~ (at your option) any later version.
  ~
  ~ Tarsius is distributed in the hope that it will be useful,
  ~ but WITHOUT ANY WARRANTY; without even the implied warranty of
  ~ MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  ~ GNU General Public License for more details.
  ~
  ~ You should have received a copy of the GNU General Public License
  ~ along with Tarsius. If not, see <http://www.gnu.org/licenses/>.
  -->
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="add" type="addType"/>

    <xs:complexType name="addType">
        <xs:sequence>
            <xs:element type="xs:string" name="description" minOccurs="1" maxOccurs="1"/>
            <xs:element type="packageType" name="package" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element type="distributionType" name="distribution" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="packageType">
        <xs:sequence>
            <xs:element type="parserType" name="parser"/>
            <xs:element type="tagsType" name="tags"/>
        </xs:sequence>
        <xs:attribute type="xs:string" name="name" use="required"/>
    </xs:complexType>

    <xs:complexType name="parserType">
        <xs:sequence>
            <xs:element type="xs:string" name="param1" minOccurs="0" maxOccurs="1"/>
            <xs:element type="xs:string" name="param2" minOccurs="0" maxOccurs="1"/>
            <xs:element type="xs:string" name="param3" minOccurs="0" maxOccurs="1"/>
        </xs:sequence>
        <xs:attribute type="xs:string" name="class" use="required"/>
    </xs:complexType>

    <xs:complexType name="tagsType">
        <xs:sequence>
            <xs:element name="tag" maxOccurs="unbounded" minOccurs="1"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="distributionType">
        <xs:sequence>
            <xs:element type="parserType" name="parser"/>
        </xs:sequence>
        <xs:attribute type="xs:string" name="version"/>
        <xs:attribute type="xs:string" name="release_name"/>
        <xs:attribute type="xs:string" name="homepage"/>
    </xs:complexType>

</xs:schema>

=== czertbytes/tarsius/tarsius-updater/src/main/resources/data/add/packages_x11.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!--
  ~ Copyright (c) 2011 by Daniel Hodan <daniel.hodan@anyd.cz>.
  ~
  ~ This file is part of Tarsius.
  ~
  ~ Tarsius is free software; you can redistribute it and/or modify
  ~ it under the terms of the GNU General Public License as published by
  ~ the Free Software Foundation, either version 3 of the License, or
  ~ (at your option) any later version.
  ~
  ~ Tarsius is distributed in the hope that it will be useful,
  ~ but WITHOUT ANY WARRANTY; without even the implied warranty of
  ~ MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  ~ GNU General Public License for more details.
  ~
  ~ You should have received a copy of the GNU General Public License
  ~ along with Tarsius. If not, see <http://www.gnu.org/licenses/>.
  -->

<add xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="add.xsd">

    <description>X11 packages</description>

    <package name="xorg">
        <parser class="cz.anyd.updater.parser.app.HtmlPageParser">
            <param1>http://www.x.org/wiki/News</param1>
            <param2><![CDATA[>X11R(.*?) released<\/a>]]></param2>
        </parser>
        <tags>
            <tag>xorg</tag>
            <tag>x11</tag>
        </tags>
    </package>

    <package name="openbox">
        <parser class="cz.anyd.updater.parser.app.HtmlPageParser">
            <param1>http://openbox.org/wiki/Openbox:News</param1>
            <param2><![CDATA[Openbox (.*?) released<\/a>]]></param2>
        </parser>
        <tags>
            <tag>openbox</tag>
            <tag>x11</tag>
            <tag>window manager</tag>
        </tags>
    </package>

    <package name="fluxbox">
        <parser class="cz.anyd.updater.parser.app.HtmlPageParser">
            <param1>http://www.fluxbox.org/download</param1>
            <param2><![CDATA[current version of Fluxbox is <b>(.*?)<\/b>.]]></param2>
        </parser>
        <tags>
            <tag>fluxbox</tag>
            <tag>x11</tag>
            <tag>window manager</tag>
        </tags>
    </package>

    <package name="compiz">
        <parser class="cz.anyd.updater.parser.app.HtmlPageParser">
            <param1>http://www.compiz.org/</param1>
            <param2><![CDATA[The latest release of Compiz is <a(?:[^>]*)>(.*?)<\/a>]]></param2>
        </parser>
        <tags>
            <tag>compiz</tag>
            <tag>x11</tag>
            <tag>window manager</tag>
        </tags>
    </package>

    <package name="slim">
        <parser class="cz.anyd.updater.parser.app.HtmlPageParser">
            <param1>http://slim.berlios.de</param1>
            <param2><![CDATA[Latest release: <a(?:[^>]*)>(.*?)<\/a>]]></param2>
        </parser>
        <tags>
            <tag>slim</tag>
            <tag>x11</tag>
            <tag>login manager</tag>
        </tags>
    </package>

    <package name="gtk+">
        <parser class="cz.anyd.updater.parser.app.HtmlPageParser">
            <param1>http://ftp.acc.umu.se/pub/gnome/sources/gtk+/3.0/</param1>
            <param2><![CDATA[<a(?:[^>]*)>LATEST-IS-(.*?)<\/a>]]></param2>
        </parser>
        <tags>
            <tag>gtk</tag>
            <tag>widget framework</tag>
        </tags>
    </package>

    <package name="qt">
        <parser class="cz.anyd.updater.parser.app.HtmlPageParser">
            <param1>http://qt.nokia.com/downloads</param1>
            <param2><![CDATA[<a(?:[^>]*)>Qt libraries (.*?) for Linux]]></param2>
        </parser>
        <tags>
            <tag>qt</tag>
            <tag>widget framework</tag>
        </tags>
    </package>

</add>

=== czertbytes/tarsius/tarsius-updater/src/main/resources/data/add/packages_database.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!--
  ~ Copyright (c) 2011 by Daniel Hodan <daniel.hodan@anyd.cz>.
  ~
  ~ This file is part of Tarsius.
  ~
  ~ Tarsius is free software; you can redistribute it and/or modify
  ~ it under the terms of the GNU General Public License as published by
  ~ the Free Software Foundation, either version 3 of the License, or
  ~ (at your option) any later version.
  ~
  ~ Tarsius is distributed in the hope that it will be useful,
  ~ but WITHOUT ANY WARRANTY; without even the implied warranty of
  ~ MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  ~ GNU General Public License for more details.
  ~
  ~ You should have received a copy of the GNU General Public License
  ~ along with Tarsius. If not, see <http://www.gnu.org/licenses/>.
  -->

<add xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="add.xsd">

    <description>Databases packages></description>

    <package name="postgresql">
        <parser class="cz.anyd.updater.parser.app.ClosureParser">
            <param1>http://www.postgresql.org/versions.rss</param1>
            <param2><![CDATA[new XmlSlurper().parseText(it).channel.item[0].title]]></param2>
        </parser>
        <tags>
            <tag>postgresql</tag>
            <tag>database</tag>
            <tag>relational</tag>
        </tags>
    </package>

    <package name="mysql">
        <parser class="cz.anyd.updater.parser.app.HtmlPageParser">
            <param1>http://www.mysql.com/downloads</param1>
            <param2><![CDATA[MySQL Community Server<\/a><span(?:[^>]*)>\(Current Generally Available Release: (.*?)\)<\/span>]]></param2>
        </parser>
        <tags>
            <tag>mysql</tag>
            <tag>database</tag>
            <tag>relational</tag>
        </tags>
    </package>

    <package name="sqlite">
        <parser class="cz.anyd.updater.parser.app.HtmlPageParser">
            <param1>http://www.sqlite.org</param1>
            <param2><![CDATA[Version (.*?)<\/a>\s+of SQLite is recommended for all new development.]]></param2>
        </parser>
        <tags>
            <tag>sqlite</tag>
            <tag>database</tag>
            <tag>relational</tag>
        </tags>
    </package>

    <package name="mongodb">
        <parser class="cz.anyd.updater.parser.app.HtmlPageParser">
            <param1>http://www.mongodb.org/downloads</param1>
            <param2><![CDATA[<div class="version">\s+(.*)\s+<\/div>]]></param2>
        </parser>
        <tags>
            <tag>mongodb</tag>
            <tag>database</tag>
            <tag>nosql</tag>
        </tags>
    </package>

    <package name="redis">
        <parser class="cz.anyd.updater.parser.app.HtmlPageParser">
            <param1>http://www.redis.io</param1>
            <param2><![CDATA[<a(?:[^>]*)>Redis (.*?) is the latest stable version.<\/a>]]></param2>
        </parser>
        <tags>
            <tag>redis</tag>
            <tag>database</tag>
            <tag>nosql</tag>
        </tags>
    </package>

    <package name="couchdb">
        <parser class="cz.anyd.updater.parser.app.HtmlPageParser">
            <param1>http://couchdb.apache.org/downloads.html</param1>
            <param2><![CDATA[<h3>(.*)<\/h3>]]></param2>
        </parser>
        <tags>
            <tag>couchdb</tag>
            <tag>database</tag>
            <tag>nosql</tag>
        </tags>
    </package>

    <package name="firebird">
        <parser class="cz.anyd.updater.parser.app.HtmlPageParser">
            <param1>http://www.ibphoenix.com/download</param1>
            <param2><![CDATA[<a href=\"\/download\/firebird\/25\"> (.*?)<\/a>]]></param2>
        </parser>
        <tags>
            <tag>firebird</tag>
            <tag>database</tag>
            <tag>relational</tag>
        </tags>
    </package>

</add>

=== czertbytes/tarsius/tarsius-updater/src/main/resources/data/add/packages_desktop_environments.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!--
  ~ Copyright (c) 2011 by Daniel Hodan <daniel.hodan@anyd.cz>.
  ~
  ~ This file is part of Tarsius.
  ~
  ~ Tarsius is free software; you can redistribute it and/or modify
  ~ it under the terms of the GNU General Public License as published by
  ~ the Free Software Foundation, either version 3 of the License, or
  ~ (at your option) any later version.
  ~
  ~ Tarsius is distributed in the hope that it will be useful,
  ~ but WITHOUT ANY WARRANTY; without even the implied warranty of
  ~ MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  ~ GNU General Public License for more details.
  ~
  ~ You should have received a copy of the GNU General Public License
  ~ along with Tarsius. If not, see <http://www.gnu.org/licenses/>.
  -->

<add xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="add.xsd">

    <description>Desktop environment packages</description>

    <package name="gnome">
        <parser class="cz.anyd.updater.parser.app.HtmlPageParser">
            <param1>http://www.gnome.org/start/stable</param1>
            <param2><![CDATA[<title>GNOME (.*?) Release Notes<\/title>]]></param2>
        </parser>
        <tags>
            <tag>gnome</tag>
            <tag>desktop environment</tag>
            <tag>gui</tag>
            <tag>gtk</tag>
        </tags>
    </package>

    <package name="kde">
        <parser class="cz.anyd.updater.parser.app.FtpDirectoryListParser">
            <param1>ftp.kde.org</param1>
            <param2>pub/kde/stable/latest/src</param2>
            <param3><![CDATA[kdebase-([^-]*?).tar.bz2]]></param3>
        </parser>
        <tags>
            <tag>kde</tag>
            <tag>desktop environment</tag>
            <tag>gui</tag>
            <tag>qt</tag>
        </tags>
    </package>

    <package name="xfce">
        <parser class="cz.anyd.updater.parser.app.HtmlPageParser">
            <param1>http://www.xfce.org/download</param1>
            <param2><![CDATA[<h2 id=\"stable\">Stable release (.*?)<\/h2>]]></param2>
        </parser>
        <tags>
            <tag>xfce</tag>
            <tag>desktop environment</tag>
            <tag>gui</tag>
            <tag>gtk</tag>
        </tags>
    </package>

    <package name="lxde">
        <parser class="cz.anyd.updater.parser.app.ClosureParser">
            <param1>http://lxde.org/download</param1>
            <param2><![CDATA["0.5.0"]]></param2>
        </parser>
        <tags>
            <tag>lxde</tag>
            <tag>desktop environment</tag>
            <tag>gui</tag>
            <tag>gtk</tag>
        </tags>
    </package>

</add>

=== czertbytes/tarsius/tarsius-updater/src/main/resources/data/add/packages_instant_messaging.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!--
  ~ Copyright (c) 2011 by Daniel Hodan <daniel.hodan@anyd.cz>.
  ~
  ~ This file is part of Tarsius.
  ~
  ~ Tarsius is free software; you can redistribute it and/or modify
  ~ it under the terms of the GNU General Public License as published by
  ~ the Free Software Foundation, either version 3 of the License, or
  ~ (at your option) any later version.
  ~
  ~ Tarsius is distributed in the hope that it will be useful,
  ~ but WITHOUT ANY WARRANTY; without even the implied warranty of
  ~ MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  ~ GNU General Public License for more details.
  ~
  ~ You should have received a copy of the GNU General Public License
  ~ along with Tarsius. If not, see <http://www.gnu.org/licenses/>.
  -->

<add xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="add.xsd">

    <description>Instant messanger packages</description>

    <package name="pidgin">
        <parser class="cz.anyd.updater.parser.app.HtmlPageParser">
            <param1>http://www.pidgin.im/</param1>
            <param2><![CDATA[Pidgin (.*?) is out]]></param2>
        </parser>
        <tags>
            <tag>pidgin</tag>
            <tag>instant messaging</tag>
            <tag>gtk</tag>
        </tags>
    </package>

    <package name="gajim">
        <parser class="cz.anyd.updater.parser.app.HtmlPageParser">
            <param1>http://www.gajim.org</param1>
            <param2><![CDATA[Gajim (.*?) is here]]></param2>
        </parser>
        <tags>
            <tag>gajim</tag>
            <tag>instant messaging</tag>
            <tag>gtk</tag>
        </tags>
    </package>

</add>

=== czertbytes/tarsius/tarsius-updater/src/main/resources/data/add/packages_mail.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!--
  ~ Copyright (c) 2011 by Daniel Hodan <daniel.hodan@anyd.cz>.
  ~
  ~ This file is part of Tarsius.
  ~
  ~ Tarsius is free software; you can redistribute it and/or modify
  ~ it under the terms of the GNU General Public License as published by
  ~ the Free Software Foundation, either version 3 of the License, or
  ~ (at your option) any later version.
  ~
  ~ Tarsius is distributed in the hope that it will be useful,
  ~ but WITHOUT ANY WARRANTY; without even the implied warranty of
  ~ MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  ~ GNU General Public License for more details.
  ~
  ~ You should have received a copy of the GNU General Public License
  ~ along with Tarsius. If not, see <http://www.gnu.org/licenses/>.
  -->

<add xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="add.xsd">

    <description>Mail packages</description>

    <package name="evolution">
        <parser class="cz.anyd.updater.parser.app.HtmlPageParser">
            <param1>http://projects.gnome.org/evolution/download.shtml</param1>
            <param2><![CDATA[Evolution<\/a><\/td>\s+<td>(.*?)<\/td>]]></param2>
        </parser>
        <tags>
            <tag>evolution</tag>
            <tag>mail</tag>
            <tag>email client</tag>
        </tags>
    </package>

    <package name="mutt">
        <parser class="cz.anyd.updater.parser.app.HtmlPageParser">
            <param1>http://www.mutt.org/</param1>
            <param2><![CDATA[<h3>Stable<\/h3>\s+<p>\s+Mutt (.*?) was released]]></param2>
        </parser>
        <tags>
            <tag>mutt</tag>
            <tag>mail</tag>
            <tag>email client</tag>
        </tags>
    </package>

    <package name="pine">
        <parser class="cz.anyd.updater.parser.app.HtmlPageParser">
            <param1>http://www.washington.edu/pine/getpine/linux.html</param1>
            <param2><![CDATA[pine_(.*?)_i386.deb]]></param2>
        </parser>
        <tags>
            <tag>pine</tag>
            <tag>mail</tag>
            <tag>email client</tag>
        </tags>
    </package>

    <package name="alpine">
        <parser class="cz.anyd.updater.parser.app.HtmlPageParser">
            <param1>http://www.washington.edu/alpine/acquire/</param1>
            <param2><![CDATA[alpine_(.*?)_i386.deb]]></param2>
        </parser>
        <tags>
            <tag>alpine</tag>
            <tag>mail</tag>
            <tag>email client</tag>
        </tags>
    </package>

    <package name="claws">
        <parser class="cz.anyd.updater.parser.app.HtmlPageParser">
            <param1>http://www.claws-mail.org/news.php</param1>
            <param2><![CDATA[Claws Mail (.*?)<b]]></param2>
        </parser>
        <tags>
            <tag>claws</tag>
            <tag>mail</tag>
            <tag>email client</tag>
        </tags>
    </package>

    <package name="sylpheed">
        <parser class="cz.anyd.updater.parser.app.HtmlPageParser">
            <param1>http://sylpheed.sraoss.jp/en/</param1>
            <param2><![CDATA[<span(?:[^>]*)>Version (.*?)<\/span>]]></param2>
        </parser>
        <tags>
            <tag>sylpheed</tag>
            <tag>mail</tag>
            <tag>email client</tag>
        </tags>
    </package>

    <package name="thunderbird">
        <parser class="cz.anyd.updater.parser.app.HtmlPageParser">
            <param1>http://releases.mozilla.org/pub/mozilla.org/thunderbird/releases/latest/linux-i686/en-US/</param1>
            <param2><![CDATA[<a(?:[^>]*)>thunderbird-(.*?).tar.bz2<\/a>]]></param2>
        </parser>
        <tags>
            <tag>thunderbird</tag>
            <tag>mail</tag>
            <tag>email client</tag>
        </tags>
    </package>

    <package name="dovecot">
        <parser class="cz.anyd.updater.parser.app.HtmlPageParser">
            <param1>http://www.dovecot.org/</param1>
            <param2><![CDATA[Released <a(?:[^>]*?)>\s+v(.*?)</a>]]></param2>
        </parser>
        <tags>
            <tag>dovecot</tag>
            <tag>mail</tag>
            <tag>mta</tag>
        </tags>
    </package>

    <package name="exim">
        <parser class="cz.anyd.updater.parser.app.HtmlPageParser">
            <param1>http://www.exim.org/</param1>
            <param2><![CDATA[<h2>Latest Version: (.*?)<\/h2>]]></param2>
        </parser>
        <tags>
            <tag>exim</tag>
            <tag>mail</tag>
            <tag>mta</tag>
        </tags>
    </package>

    <package name="fetchmail">
        <parser class="cz.anyd.updater.parser.app.HtmlPageParser">
            <param1>http://fetchmail.berlios.de/index.html</param1>
            <param2><![CDATA[<h1>NEWS: FETCHMAIL (.*?) RELEASE<\/h1>]]></param2>
        </parser>
        <tags>
            <tag>fetchmail</tag>
            <tag>mail</tag>
            <tag>email client</tag>
        </tags>
    </package>

    <package name="postfix">
        <parser class="cz.anyd.updater.parser.app.HtmlPageParser">
            <param1>http://ftp.porcupine.org/mirrors/postfix-release/index.html</param1>
            <param2><![CDATA[<a href=\"official\/postfix-(.*?).tar.gz\">Source code<\/a>]]></param2>
        </parser>
        <tags>
            <tag>postfix</tag>
            <tag>mail</tag>
            <tag>mta</tag>
        </tags>
    </package>

    <package name="courier">
        <parser class="cz.anyd.updater.parser.app.HtmlPageParser">
            <param1>http://www.courier-mta.org/download.php</param1>
            <param2><![CDATA[courier-(.*?).tar.bz2]]></param2>
        </parser>
        <tags>
            <tag>courier</tag>
            <tag>mail</tag>
            <tag>mta</tag>
        </tags>
    </package>

    <package name="cyrus">
        <parser class="cz.anyd.updater.parser.app.HtmlPageParser">
            <param1>http://www.cyrusimap.org/</param1>
            <param2><![CDATA[<p>Version: (.*?)<\/p>]]></param2>
        </parser>
        <tags>
            <tag>cyrus</tag>
            <tag>mail</tag>
            <tag>mta</tag>
        </tags>
    </package>

    <package name="bogofilter">
        <parser class="cz.anyd.updater.parser.app.HtmlPageParser">
            <param1>http://bogofilter.sourceforge.net/</param1>
            <param2><![CDATA[<font(?:[^>]*?)>&nbsp;v(.*?)\s+<\/font>]]></param2>
        </parser>
        <tags>
            <tag>bogofilter</tag>
            <tag>mail</tag>
            <tag>spam filter</tag>
        </tags>
    </package>

    <package name="spamassassin">
        <parser class="cz.anyd.updater.parser.app.HtmlPageParser">
            <param1>http://spamassassin.apache.org/downloads.cgi</param1>
            <param2><![CDATA[<h3>Released version, (.*?)<\/h3>]]></param2>
        </parser>
        <tags>
            <tag>spamassassin</tag>
            <tag>mail</tag>
            <tag>spam filter</tag>
        </tags>
    </package>

    <package name="kolab">
        <parser class="cz.anyd.updater.parser.app.HtmlPageParser">
            <param1>http://www.kolab.org/download.html</param1>
            <param2><![CDATA[current stable release (.*?)\s+]]></param2>
        </parser>
        <tags>
            <tag>kolab</tag>
            <tag>groupware</tag>
        </tags>
    </package>

    <package name="citadel">
        <parser class="cz.anyd.updater.parser.app.HtmlPageParser">
            <param1>http://www.citadel.org/doku.php?id=news:start</param1>
            <param2><![CDATA[<a(?:[^>]*)>Citadel (.*?) released<\/a>]]></param2>
        </parser>
        <tags>
            <tag>citadel</tag>
            <tag>mail</tag>
            <tag>groupware</tag>
        </tags>
    </package>

</add>

=== czertbytes/tarsius/tarsius-updater/src/main/resources/data/add/packages_web_browser.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!--
  ~ Copyright (c) 2011 by Daniel Hodan <daniel.hodan@anyd.cz>.
  ~
  ~ This file is part of Tarsius.
  ~
  ~ Tarsius is free software; you can redistribute it and/or modify
  ~ it under the terms of the GNU General Public License as published by
  ~ the Free Software Foundation, either version 3 of the License, or
  ~ (at your option) any later version.
  ~
  ~ Tarsius is distributed in the hope that it will be useful,
  ~ but WITHOUT ANY WARRANTY; without even the implied warranty of
  ~ MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  ~ GNU General Public License for more details.
  ~
  ~ You should have received a copy of the GNU General Public License
  ~ along with Tarsius. If not, see <http://www.gnu.org/licenses/>.
  -->

<add xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="add.xsd">

    <description>Web browser packages</description>

    <package name="firefox">
        <parser class="cz.anyd.updater.parser.app.HtmlPageParser">
            <param1>http://releases.mozilla.org/pub/mozilla.org/firefox/releases/latest/linux-i686/en-US/</param1>
            <param2><![CDATA[<a(?:[^>]*)>firefox-(.*?).tar.bz2<\/a>]]></param2>
        </parser>
        <tags>
            <tag>firefox</tag>
            <tag>web browser</tag>
            <tag>gui</tag>
            <tag>gtk</tag>
        </tags>
    </package>

    <package name="chromium">
        <parser class="cz.anyd.updater.parser.app.HtmlPageParser">
            <param1>http://omahaproxy.appspot.com/</param1>
            <param2><![CDATA[linux,stable,([^,]*),(?:.*?)]]></param2>
        </parser>
        <tags>
            <tag>chromium</tag>
            <tag>web browser</tag>
            <tag>gui</tag>
            <tag>gtk</tag>
        </tags>
    </package>

    <package name="midori">
        <parser class="cz.anyd.updater.parser.app.HtmlPageParser">
            <param1>http://git.xfce.org/apps/midori/plain/ChangeLog</param1>
            <param2><![CDATA[v([^:]*):]]></param2>
        </parser>
        <tags>
            <tag>midori</tag>
            <tag>web browser</tag>
            <tag>gui</tag>
            <tag>gtk</tag>
        </tags>
    </package>

</add>

=== czertbytes/tarsius/tarsius-updater/src/main/resources/data/add/distributions_debian.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!--
  ~ Copyright (c) 2011 by Daniel Hodan <daniel.hodan@anyd.cz>.
  ~
  ~ This file is part of Tarsius.
  ~
  ~ Tarsius is free software; you can redistribute it and/or modify
  ~ it under the terms of the GNU General Public License as published by
  ~ the Free Software Foundation, either version 3 of the License, or
  ~ (at your option) any later version.
  ~
  ~ Tarsius is distributed in the hope that it will be useful,
  ~ but WITHOUT ANY WARRANTY; without even the implied warranty of
  ~ MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  ~ GNU General Public License for more details.
  ~
  ~ You should have received a copy of the GNU General Public License
  ~ along with Tarsius. If not, see <http://www.gnu.org/licenses/>.
  -->

<add xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="add.xsd">

    <description>Debian distributions</description>

    <distribution version="6.0" release_name="squeeze" homepage="">
        <parser class="cz.anyd.updater.parser.distro.DebianParser" />
    </distribution>

    <distribution version="7.0" release_name="wheezy" homepage="">
        <parser class="cz.anyd.updater.parser.distro.DebianParser" />
    </distribution>

    <distribution version="" release_name="sid" homepage="">
        <parser class="cz.anyd.updater.parser.distro.DebianParser" />
    </distribution>

</add>

=== czertbytes/tarsius/tarsius-updater/src/main/resources/data/add/packages_shell.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!--
  ~ Copyright (c) 2011 by Daniel Hodan <daniel.hodan@anyd.cz>.
  ~
  ~ This file is part of Tarsius.
  ~
  ~ Tarsius is free software; you can redistribute it and/or modify
  ~ it under the terms of the GNU General Public License as published by
  ~ the Free Software Foundation, either version 3 of the License, or
  ~ (at your option) any later version.
  ~
  ~ Tarsius is distributed in the hope that it will be useful,
  ~ but WITHOUT ANY WARRANTY; without even the implied warranty of
  ~ MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  ~ GNU General Public License for more details.
  ~
  ~ You should have received a copy of the GNU General Public License
  ~ along with Tarsius. If not, see <http://www.gnu.org/licenses/>.
  -->

<add xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="add.xsd">

    <description>Shell packages</description>

    <package name="bash">
        <parser class="cz.anyd.updater.parser.app.FtpDirectoryListParser">
            <param1>ftp.gnu.org</param1>
            <param2>gnu/bash/</param2>
            <param3><![CDATA[bash-([^doc]*?).tar.gz]]></param3>
        </parser>
        <tags>
            <tag>bash</tag>
            <tag>shell</tag>
        </tags>
    </package>

    <package name="dash">
        <parser class="cz.anyd.updater.parser.app.HtmlPageParser">
            <param1>http://gondor.apana.org.au/~herbert/dash/files/</param1>
            <param2><![CDATA[<a(?:[^>]*)>dash-(.*?).tar.gz<\/a>]]></param2>
        </parser>
        <tags>
            <tag>dash</tag>
            <tag>shell</tag>
        </tags>
    </package>

    <package name="tcsh">
        <parser class="cz.anyd.updater.parser.app.HtmlPageParser">
            <param1>http://www.tcsh.org/MostRecentRelease</param1>
            <param2><![CDATA[The most recent Tcsh release is <strong>(.*?)<\/strong>.]]></param2>
        </parser>
        <tags>
            <tag>tcsh</tag>
            <tag>shell</tag>
        </tags>
    </package>

    <package name="zsh">
        <parser class="cz.anyd.updater.parser.app.HtmlPageParser">
            <param1>http://zsh.sourceforge.net/FAQ/zshfaq01.html</param1>
            <param2><![CDATA[Zsh (.*?) is the latest production version.]]></param2>
        </parser>
        <tags>
            <tag>zsh</tag>
            <tag>shell</tag>
        </tags>
    </package>

</add>
